// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJv3B62mXzo_HEUyskt_dixJKow3rGbLA',
    appId: '1:801750761432:web:bfc065c1be9a7f50487cad',
    messagingSenderId: '801750761432',
    projectId: 'gunas-employee-attendance',
    authDomain: 'gunas-employee-attendance.firebaseapp.com',
    storageBucket: 'gunas-employee-attendance.firebasestorage.app',
    measurementId: 'G-Z5SR7CH18B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk0JyB4LscetQDRbtqttnBV7FohlVg3gs',
    appId: '1:801750761432:android:98026c8b5d3cf5e1487cad',
    messagingSenderId: '801750761432',
    projectId: 'gunas-employee-attendance',
    storageBucket: 'gunas-employee-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO5S7AfXCfQ_53qbxZoMc-fiVxIX0aKcs',
    appId: '1:801750761432:ios:8dd5bfe2a9338276487cad',
    messagingSenderId: '801750761432',
    projectId: 'gunas-employee-attendance',
    storageBucket: 'gunas-employee-attendance.firebasestorage.app',
    iosBundleId: 'com.example.gunasEmployeeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO5S7AfXCfQ_53qbxZoMc-fiVxIX0aKcs',
    appId: '1:801750761432:ios:8dd5bfe2a9338276487cad',
    messagingSenderId: '801750761432',
    projectId: 'gunas-employee-attendance',
    storageBucket: 'gunas-employee-attendance.firebasestorage.app',
    iosBundleId: 'com.example.gunasEmployeeAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJv3B62mXzo_HEUyskt_dixJKow3rGbLA',
    appId: '1:801750761432:web:4dfa4ce542deaf7b487cad',
    messagingSenderId: '801750761432',
    projectId: 'gunas-employee-attendance',
    authDomain: 'gunas-employee-attendance.firebaseapp.com',
    storageBucket: 'gunas-employee-attendance.firebasestorage.app',
    measurementId: 'G-PXKVGN37FE',
  );

}