// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUkIi2vfJDaZbd9s0XyyXPDfWDIUWxqLg',
    appId: '1:1054469745762:web:1865804ad450fd0883b53b',
    messagingSenderId: '1054469745762',
    projectId: 'gunas-attendance',
    authDomain: 'gunas-attendance.firebaseapp.com',
    storageBucket: 'gunas-attendance.firebasestorage.app',
    measurementId: 'G-07SGS7SHDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwd33cO1aA0vicTIK50G-UfEz8f1cLHqw',
    appId: '1:1054469745762:android:94d134ab00c7b77183b53b',
    messagingSenderId: '1054469745762',
    projectId: 'gunas-attendance',
    storageBucket: 'gunas-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcoN1vuegb8DLlNoKfYJTVz97zy6i_-cw',
    appId: '1:1054469745762:ios:ba24db030cdf626383b53b',
    messagingSenderId: '1054469745762',
    projectId: 'gunas-attendance',
    storageBucket: 'gunas-attendance.firebasestorage.app',
    iosBundleId: 'com.example.gunasEmployeeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcoN1vuegb8DLlNoKfYJTVz97zy6i_-cw',
    appId: '1:1054469745762:ios:ba24db030cdf626383b53b',
    messagingSenderId: '1054469745762',
    projectId: 'gunas-attendance',
    storageBucket: 'gunas-attendance.firebasestorage.app',
    iosBundleId: 'com.example.gunasEmployeeAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUkIi2vfJDaZbd9s0XyyXPDfWDIUWxqLg',
    appId: '1:1054469745762:web:1fb2a391b390057183b53b',
    messagingSenderId: '1054469745762',
    projectId: 'gunas-attendance',
    authDomain: 'gunas-attendance.firebaseapp.com',
    storageBucket: 'gunas-attendance.firebasestorage.app',
    measurementId: 'G-8SJXBZRRK1',
  );

}